# https://drfrankenstein.co.uk/category/media-management/
version: '3.8'
services:
  # VPN
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=Netherlands
      - HTTPPROXY=on
      - SHADOWSOCKS=on
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${CONFIG_ROOT}/gluetun:/gluetun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  # Torrents
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/transmission:/config
      - ${DOWNLOADS_ROOT}:/downloads
      - ${DOWNLOADS_ROOT}/torrent-blackhole:/watch

  # API for torrents
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/jackett:/config
      - ${DOWNLOADS_ROOT}/torrent-blackhole:/downloads
    ports:
      - 9117:9117

  # Usenet
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/nzbget:/config
      - ${DOWNLOADS_ROOT}:/downloads
    ports:
      - 6789:6789

  # TV
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/sonarr:/config
      - ${MEDIA_ROOT}/tv:/tv
      - ${DOWNLOADS_ROOT}:/downloads
    ports:
      - 8989:8989

  # Movies
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/radarr:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${DOWNLOADS_ROOT}:/downloads
    ports:
      - 7878:7878

  # Subtitles
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${MEDIA_ROOT}/tv:/tv
    ports:
      - 6767:6767

  # Watching
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CONFIG_ROOT}/plex:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${MEDIA_ROOT}/tv:/tv
      - ${MEDIA_ROOT}/youtube:/youtube
    ports:
      - 32400:32400

  # Media requests
  overseerr:
    container_name: overseerr
    image: linuxserver/overseerr:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/overseerr:/config
    ports:
      - 5055:5055

  # Music
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MUSIC_ROOT}:/data
      - ${CONFIG_ROOT}/lidarr:/config
      - ${DOWNLOADS_ROOT}:/downloads
    ports:
      - 8686:8686
  
  # YouTube
  youtube:
    container_name: youtube
    image: tzahi12345/youtubedl-material:latest
    restart: unless-stopped
    network_mode: docker_default
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - USER=rtmacdonald
      - ytdl_default_downloader=yt-dlp
      - ytdl_use_local_db=true
      - ytdl_port=9998
      - write_ytdl_config=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT}/youtube/users:/app/users:rw
      - ${MEDIA_ROOT}/youtube/subscriptions:/app/subscriptions:rw
      - ${MUSIC_ROOT}/youtube:/app/audio:rw
      - ${MEDIA_ROOT}/youtube/video:/app/video:rw
      - ${CONFIG_ROOT}/youtubedl:/app/appdata:rw
    ports:
      - 9998:9998/tcp